name: Haskell Auto
favicon: null
layout_spectrum: 0.9281894532032311
typography_spectrum: 0.13043051934801042
title: Haskell Auto
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a9348'
    - '#211f20'
    - '#828282'
    - '#a6c7b4'
  brandStrength: 0.6875
  lightness: 0.6144576841033995
  saturation: 0.8296121780294925
  rhythmicContrast: 0.9490441384259611
purpose: []
