name: Haskell Auto
favicon: null
layout_spectrum: 0.54465
typography_spectrum: 1
title: Haskell Auto
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a9348'
    - '#211f20'
    - '#828282'
    - '#a6c7b4'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
